### PR TITLE
vue: enable vue on ci

### PR DESCRIPTION
**Pull request by jbedard**

### CODE REVIEW

**Comment by alexeagle** [comment]
It fails because it has no tests. You could just add a `build_test` as a placeholder, though the fact that we have a bug filed against this example suggests we should have a real test for the bundle output.

**Comment by jbedard** [comment]
Yeah I forgot you mentioned that earlier. I'd like to add at least a basic test instead of just building it

**Comment by jbedard** [comment]
@alexeagle I think I'd like to merge this now just to get it running on CI and I'll create a task for adding tests...

**Review by alexeagle — APPROVED** [review]
Sure, small steps
Are always better

**Comment by jbedard** [comment]
https://github.com/aspect-build/bazel-examples/issues/77

**Pull request merged**
