### PR TITLE
add create-react-app example

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by heartless-clown** [comment]
@alexeagle if you don't mind take a look, here is an example repository where I was able to get react-scripts to work with aspect_rules_js.

- https://github.com/heartless-clown/bazel_aspect_rules_js_react

Though the solution is far from ideal, maybe it will be helpful in making a proper react-scripts example.

**Comment by heartless-clown** [comment]
@alexeagle you were probably looking at the wrong branch. 

- [ejected](https://github.com/heartless-clown/bazel_aspect_rules_js_react/tree/ejected)
- [non-ejected](https://github.com/heartless-clown/bazel_aspect_rules_js_react/tree/non-ejected)

**Comment by alexeagle** [comment]
Yeah that was it, thanks. Do you know what was the critical fix/fixes to get past the webpack syntax error in my branch?

**Comment by alexeagle** [comment]
Looking over what you did, it's very useful thanks!

> the solution is far from ideal
anything specific you had in mind that should be improved?

I'll take a look at porting the fixes to this repo.

**Review by gregmagolan — APPROVED** [review]
🌮

**Comment by alexeagle** [comment]
For anyone reading through the history, Greg is really the expert here and should be consulted with any and all questions 😜

**Pull request merged**
