### PR TITLE
use bazel-lib tar instead of rules_pkg

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Review by thesayyn — APPROVED** [review]
NEAT!  goodbye rules_pkg

**Comment by alexeagle** [comment]
@thesayyn I dropped the two-layers feature here though. Maybe we should restore that before landing? should we use an mtree manipulation library to filter the tar manifest to produce two tars?

**Comment by thesayyn** [comment]
> @thesayyn I dropped the two-layers feature here though. Maybe we should restore that before landing? should we use an mtree manipulation library to filter the tar manifest to produce two tars?

maybe we should make some other example for that? I'd like to explore what's out there that could help us manipulate mtrees

**Comment by alexeagle** [comment]
It was pretty easy with just plain `grep` - PTAL

**Review by thesayyn — APPROVED** [review]
mtree exquisite.

**Pull request merged**
