### PR TITLE
Prisma Example

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by alexeagle** [comment]
Awesome, do you mind adding some README.md to it with some notes about what is prisma and anything a reader should know about the example? Just a brain dump of what you currently understand.

**Comment by gzm0** [comment]
Added a README. PTAL.

**Comment by alexeagle** [comment]
you can `pre-commit install` in the root of the git repo, and you'll get auto-formatting fixes on commit

**Comment by gzm0** [comment]
> you can pre-commit install in the root of the git repo, and you'll get auto-formatting fixes on commit

Done (I think you need to approve the git workflows again).

**Pull request merged**
