### PR TITLE
chore: upgrade vite, no longer need patch

### PR DESCRIPTION
**Pull request by alexeagle**
Manually tested that `bazel run :vite` still serves the app

### CODE REVIEW

**Comment by jbedard** [comment]
@alexeagle does it need to be enabled in CI still?

**Comment by alexeagle** [comment]
Does what need to be enabled?

**Comment by jbedard** [comment]
https://github.com/aspect-build/bazel-examples/blob/5e339960724b0f300dccb02c38113dbe8998d58b/.github/workflows/ci.yaml#L34-L35

**Comment by alexeagle** [comment]
ah, thanks I didn't know that was there, yes we should fix the todo

**Comment by alexeagle** [comment]
oh it's just `ERROR: No test targets were found, yet testing was requested` I guess it does need a test

**Pull request merged**
