### PR TITLE
example(angular-ngc): add custom_postinstall ngcc example

### PR DESCRIPTION
**Pull request by jackvincentnz**
Adds `ngcc` to the rules_js bin, adds a peer dep on `@angular/compiler-cli` and runs `ngcc` as a `custom_postinstall`.

### CODE REVIEW

**Comment by jbedard** [comment]
Could we add one usage of the library within the test app?

if it's easy would you be able to also update the `angular` example? Hopefully just copy + paste?

**Comment by jackvincentnz** [comment]
> Could we add one usage of the library within the test app?
> 
> if it's easy would you be able to also update the `angular` example? Hopefully just copy + paste?

Yes, I can add these.

**Comment by jackvincentnz** [comment]
> Could we add one usage of the library within the test app?

@jbedard Added to both angular examples. I haven't figured out how to serve the `/angular` one locally to test it, but the build passes.

**Review by jbedard — APPROVED** [review]

**Comment by jbedard** [comment]
Awesome, thanks @jackvincentnz! 👍

**Pull request merged**
